### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mrsertich** [Mottokrosh/Sheet#124]
I don't normally do this, but I'm having an issue at a UX point.  I had been logging in through google for the last year, but today the authorization sent me to a blank screen.  No options for sheets and I needed to reload the page to try again.  In order to get around the issue, I tried creating a github account with my google email and logging in that way, but I got a new page instead.  No character sheets, but I could make a new one.  Finally, I checked the issues to see if anything was being resolved.  Unfortunately, I saw that linking the google account to the github account was a resolved issue, but I couldn't find any way to link the two at all.  Is there a way to link the two properly for a layman and if so, how?

**Comment by edreeseg** [comment]
Going to take a look at this and see if I can replicate - my group continues to use Google OAuth seemingly without issue, but there could be some difference. In the meantime, I've attached a screenshot below of what it looks like after I hit login - in this case, a separate window has opened listing my Google accounts and prompting me to select one. Could it possibly be there's a window hiding cheekily somewhere in the background?

<img width="1684" height="1138" alt="Image" src="https://github.com/user-attachments/assets/192dd9ac-4ca8-45ec-8d69-ec0e332b7516" />

**Comment by edreeseg** [comment]
Update - on my end, updating google-auth-library to ^5.0.0 and making changes associated with GIS fixed the issue. Originally I'd been getting a payload indicating
```
{
  blocked: true,
  suppressed: false,
  valid: true
}
```
And I have seen speculation this is due to the deprecation and sunsetting of Google Sign-In JavaScript Platform Library for web. After making these changes and updating to use Google's button, I can no longer reproduce the issue and am able to log in successfully.

**Comment by edreeseg** [comment]
@AzriellaVeRaon @mrsertich Can you check if this is still happening?

**Comment by mrsertich** [comment]
It is fixed on my end.

**Comment by edreeseg** [comment]
Going to close as this seems to be addressed - if any issues persist, please let me know.
